[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NODE_NAMESPACE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
